name: Plugin CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          ditributions: 'adopt'
      - name: Build JAR
        run: mvn --batch-mode --update-snapshots package
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: target/SIMPS*.jar
